apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: angular
spec:
  template:
    spec:
      containers:
        - image: ttl.sh/angularapp:2h
          ports:
            - containerPort: 80
          env:
            - name: TARGET
              value: "World"
